name: Database scripts execution
on:
  push:
    branches:
    - main
jobs:
  getDbEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Get Database type
        id: environment
        run: |
          ${{ dbType }}='mysql'
          if [ "${{ secrets.dbType }}" != "" ]; then
              ${{ dbType }}=${{ secrets.dbType }}
          fi
           echo "::set-output name=DBTYPE::${dbType}"
           echo "Database Type : ${dbType}"
    outputs:
      ${{ dbType }}=: ${{ steps.environment.outputs.dbType }}

  runDB: 
    name: 'Run MYSQL'
    runs-on: ubuntu-latest

    defaults:
        run: 
          shell: bash

    steps:
      - name: Setup MYSQL
        if: ${{ dbType }} == 'mysql'
        uses: Azure/mysql@v1
        with:
            server-name: ${{ env.DB_SERVER_NAME }}
            connection-string: ${{ env.DB_CONNECTION_STRING }}
            username: ${{ secrets.DB_USERNAME }}
            password: ${{ secrets.DB_PASSWORD }}
            database: ${{ secrets.DB_DATABASE }}
            sql-file: ${{ secrets.SQL_FILE }}
            arguments: ${{ secrets.ARGUMENTS }} # optional

      - name: Setup Azure PostgreSQL
        if: ${{ dbType }} == 'postgresql'
        uses: Azure/postgresql@v1
        with:
            server-name: ${{ secrets.DB_SERVER_NAME }}
            connection-string: ${{ secrets.DB_CONNECTION_STRING }}
            plsql-file: ${{ secrets.PLSQL_FILE }}
            arguments: ${{ secrets.ARGUMENTS }} # optional

     
